//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team7ADProjectMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class disbAnalysi
    {
        public string DepartmentName { get; set; }
        public string Description { get; set; }
        public string ItemNo { get; set; }
        public Nullable<int> DeliveredQuantity { get; set; }
        public string CategoryName { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
    }
}
