//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team7ADProjectMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int NotificationId { get; set; }
        public int EmployeeId { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public string Intent { get; set; }
        public string PageHeader { get; set; }
        public string PageId { get; set; }
        public string ExtraDetail { get; set; }
    }
}
