//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team7ADProjectMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requisition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Requisition()
        {
            this.RequisitionDetails = new HashSet<RequisitionDetail>();
        }
    
        public int RequisitionId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> OrderedDate { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string RequisitionStatus { get; set; }
        public string Comment { get; set; }
        public Nullable<int> RetrievalId { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequisitionDetail> RequisitionDetails { get; set; }
        public virtual Retrieval Retrieval { get; set; }
    }
}
