//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team7ADProjectMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockCard
    {
        public System.DateTime Date { get; set; }
        public string Dept_Supplier { get; set; }
        public string AdjustedQuantity { get; set; }
        public string ItemNo { get; set; }
        public string Description { get; set; }
    }
}
